services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #      - MYSQL_USER=root
      #      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_HOST=%
#    volumes:
#      - ./data/mysql:/data/mysql
    ports:
      - "3306:3306"
    networks:
      - cloud-network

  student-management-system:
    image: migi987/student-management-system:latest
    container_name: student-management-system
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - cloud-network
    depends_on:
      - mysql

networks:
  cloud-network:
    driver: bridge